wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.25.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1668820282.554238
    t:
      1:
      - 11
      - 12
      - 45
      - 49
      - 55
      2:
      - 11
      - 12
      - 45
      - 49
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.13.5
      6: 4.25.0.dev0
      8:
      - 5
